name: Terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        VER=$(cat .terraform-version)
        echo "TF_VERSION=$VER" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './test/go.mod'
        cache-dependency-path: './test/go.sum'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run Terratest
      run: |
        go test -v ./test/...
