name: Terratest

on:
  - workflow_call

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: ./.github/actions/install-tf
      with:
        terraform-version-file: tf/.terraform-version

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version-file: 'test/go.mod'
        cache-dependency-path: 'test/go.sum'

    - name: Install dependencies
      run: |
        cd test
        go mod tidy

    - name: Run Terratest
      run: |
        cd test
        go test -v
