name: Terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set variables
      run: |
        VER=$(cat tf/.terraform-version)
        echo "TF_VERSION=$VER" >> $GITHUB_ENV
        echo "Using Terraform version $VER"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version-file: 'test/go.mod'
        cache-dependency-path: 'test/go.sum'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Install dependencies
      run: |
        cd test
        go mod tidy

    - name: Run Terratest
      run: |
        cd test
        go test -v
