name: "tflint"

on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read

jobs:
  tflint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Terraform
      uses: ./.github/actions/install-tf
      with:
        terraform-version-file: tf/.terraform-version

    - uses: terraform-linters/setup-tflint@v4
      name: Setup tflint
      with:
        tflint_version: v0.53.0

    - name: Show version
      run: tflint --version

    - name: Terraform Format
      working-directory: tf
      run: terraform fmt -diff -check
    
    - name: Terraform lint
      working-directory: tf
      run: tflint
