name: "TFLint"

on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read

jobs:
  tflintandfmt:
    name: 'Terraform Lint and Format'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.53.0

    - name: Show version
      run: tflint --version

    - name: Set variables
      run: |
          VER=$(cat tf/.terraform-version)
          echo "TF_VERSION=$VER" >> $GITHUB_ENV
          echo "Using Terraform version $VER"

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: tf
      run: terraform fmt -check
    
    - name: Terraform lint
      working-directory: tf
      run: tflint
